import type { ContentItem } from './schema';

export const discoveryContent: ContentItem[] = [
  {
    id: "discovery-philosophy",
    module: "discovery",
    type: "fact",
    title: "Discovery Philosophy",
    body: "Lead with their world, not Devin. No feature is mentioned until the customer has named a pain in their own words. Move from open → quantifying → implication (loosely SPIN). Always convert to a number or a tradeoff. Capture their words as product signal (a named JD behavior).",
    persona: ["CTO", "CIO", "Security"],
    tags: ["discovery", "methodology", "spin"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 0,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-prioritization-1",
    module: "discovery",
    type: "question",
    title: "CTO Prioritization: Time Allocation",
    body: "\"You own engineering foundations and AI for the Group. When you look at your engineers' time, what proportion goes to building new capability versus maintaining and modernising what already exists?\"",
    persona: ["CTO"],
    tags: ["discovery", "cto", "prioritization", "time-allocation"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 1,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-prioritization-2",
    module: "discovery",
    type: "question",
    title: "CTO Prioritization: Deferred Modernisation Cost",
    body: "\"How do you currently decide what modernisation work gets done versus deferred — and what does 'deferred' cost you later?\"",
    persona: ["CTO"],
    tags: ["discovery", "cto", "prioritization", "tech-debt"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 2,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-risk-1",
    module: "discovery",
    type: "question",
    title: "CTO Risk: Version Currency at Scale",
    body: "\"You drove DevSecOps at HSBC. How do you keep hundreds of repos current on framework and dependency versions without it becoming a tax on your best engineers?\"",
    persona: ["CTO"],
    tags: ["discovery", "cto", "risk", "devsecops"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 3,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-risk-2",
    module: "discovery",
    type: "question",
    title: "CTO Risk: End-of-Support Scramble",
    body: "\"When a framework or a runtime hits end-of-support, what does the remediation scramble look like across your estate today?\"",
    persona: ["CTO"],
    tags: ["discovery", "cto", "risk", "eol"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 4,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-opportunity-cost",
    module: "discovery",
    type: "question",
    title: "CTO Opportunity Cost: Capacity Redeployment",
    body: "\"If you could take the repeatable modernisation work off your senior engineers entirely — verified, reviewed, audit-logged — where would you redeploy that capacity first?\"",
    persona: ["CTO"],
    tags: ["discovery", "cto", "opportunity-cost"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 5,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cto-qualifier",
    module: "discovery",
    type: "question",
    title: "CTO Trap-Free Qualifier",
    body: "\"You've deployed agentic AI at scale before. What stopped it from going further — was it the autonomy ceiling, the verification/trust gap, or the governance model?\"\n\n*Whatever he says is a Devin differentiator: interactive planning, test-verify loop, or VPC + Devin Review.*",
    persona: ["CTO"],
    tags: ["discovery", "cto", "qualifier", "trap-free"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 6,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-prioritization-1",
    module: "discovery",
    type: "question",
    title: "CIO Prioritization: Delivery Gap",
    body: "\"You own business-aligned delivery across the Group. Where is the gap today between what the business wants shipped and the engineering capacity you can free up to ship it?\"",
    persona: ["CIO"],
    tags: ["discovery", "cio", "prioritization", "capacity-gap"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 7,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-prioritization-2",
    module: "discovery",
    type: "question",
    title: "CIO Prioritization: Non-Differentiating Work Load",
    body: "\"How much of your delivery roadmap is consumed by mandatory, non-differentiating work — upgrades, migrations, compliance remediation?\"",
    persona: ["CIO"],
    tags: ["discovery", "cio", "prioritization", "roadmap"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 8,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-risk-1",
    module: "discovery",
    type: "question",
    title: "CIO Risk: Legacy Delivery Risk",
    body: "\"When you model delivery risk, how much of it traces back to legacy or out-of-date components that nobody has capacity to modernise?\"",
    persona: ["CIO"],
    tags: ["discovery", "cio", "risk", "legacy"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 9,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-opportunity-cost-1",
    module: "discovery",
    type: "question",
    title: "CIO Opportunity Cost: Engineer-Years Headline",
    body: "\"If we expressed your modernisation backlog in senior-engineer-years, what's the headline number — and what would the business do with even a third of that capacity back?\"",
    persona: ["CIO"],
    tags: ["discovery", "cio", "opportunity-cost", "quantifying"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 10,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-opportunity-cost-2",
    module: "discovery",
    type: "question",
    title: "CIO Opportunity Cost: Outcome-Priced Engineering",
    body: "\"Today you buy engineering as capacity — headcount and licenses. If you could instead buy completed, verified outcomes at a known cost per unit for the repeatable work, how would that change how you plan a roadmap?\"\n\n*This is the thesis, asked as a question.*",
    persona: ["CIO"],
    tags: ["discovery", "cio", "opportunity-cost", "thesis-question"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 11,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-opportunity-cost-3",
    module: "discovery",
    type: "question",
    title: "CIO Opportunity Cost: Measuring AI Value",
    body: "\"When you've bought AI tooling before, how did you measure whether it actually paid off — versus just tracking that people were using it? What would contractual accountability for delivered value be worth to you?\"\n\n*Sets up the guarantee: vendor accountable for value, not activity.*",
    persona: ["CIO"],
    tags: ["discovery", "cio", "opportunity-cost", "guarantee-setup"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 12,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "cio-qualifier",
    module: "discovery",
    type: "question",
    title: "CIO Trap-Free Qualifier",
    body: "\"Goldman framed AI as a 'hybrid workforce.' For CBA, what would have to be true — commercially and operationally — for an agent to be a trusted line item in your delivery model rather than an experiment?\"",
    persona: ["CIO"],
    tags: ["discovery", "cio", "qualifier", "trap-free", "goldman"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 13,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-prioritization-1",
    module: "discovery",
    type: "question",
    title: "Security Prioritization: Competing Priorities",
    body: "\"When mandatory security work — patching, vulnerability remediation, version currency — competes with feature delivery for the same engineers, who wins, and what's the backlog of security-driven work waiting on capacity?\"",
    persona: ["Security"],
    tags: ["discovery", "security", "prioritization", "backlog"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 14,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-prioritization-2",
    module: "discovery",
    type: "question",
    title: "Security Prioritization: CPS 234 Evidence Burden",
    body: "\"Under CPS 234, how do you currently evidence that your code estate is current and remediated — and how much manual effort is that evidence?\"",
    persona: ["Security"],
    tags: ["discovery", "security", "prioritization", "cps-234", "evidence"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 15,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-risk-1",
    module: "discovery",
    type: "question",
    title: "Security Risk: Exposure Window",
    body: "\"What's your exposure window today between a CVE or an end-of-support notice and remediation across every affected repo?\"",
    persona: ["Security"],
    tags: ["discovery", "security", "risk", "exposure-window", "cve"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 16,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-risk-2",
    module: "discovery",
    type: "question",
    title: "Security Risk: Demonstrable Action",
    body: "\"Your peers have said in court that 'demonstrable action beats documented intent.' How do you make remediation demonstrable at the pace regulators now expect?\"",
    persona: ["Security"],
    tags: ["discovery", "security", "risk", "demonstrable-action"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 17,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-opportunity-cost-1",
    module: "discovery",
    type: "question",
    title: "Security Opportunity Cost: Parallel Remediation",
    body: "\"If remediation could be executed in parallel across every repo, with a human approving each change and a full audit trail, what would that do to your exposure window — and your audit-evidence burden?\"",
    persona: ["Security"],
    tags: ["discovery", "security", "opportunity-cost", "parallel"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 18,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-opportunity-cost-2",
    module: "discovery",
    type: "question",
    title: "Security: Control Requirements Probe",
    body: "\"What would you need to see — deployment model, source controls, review trail — before you'd let an agent touch a production security codebase?\"\n\n*Hands you the control-stack answer: VPC dev box in-VPC, RAG restricted to internal repos, human approval gate, every change a reviewable PR, Devin Review, DeepWiki audit trail.*",
    persona: ["Security"],
    tags: ["discovery", "security", "opportunity-cost", "controls"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 19,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "security-qualifier",
    module: "discovery",
    type: "question",
    title: "Security Trap-Free Qualifier",
    body: "\"Is your bigger risk an agent doing too much autonomously, or your best people being too buried in repetitive remediation to focus on real threats?\"\n\n*Either answer favours governed Devin.*",
    persona: ["Security"],
    tags: ["discovery", "security", "qualifier", "trap-free"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 20,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  },
  {
    id: "discovery-demo-handoff",
    module: "discovery",
    type: "story-beat",
    title: "Discovery → Demo Handoff",
    body: "\"You've told me [X senior-engineer-years] go to repeatable modernisation, your exposure window is [Y], and your audit evidence is manual. Let me show you that exact work — an Angular upgrade on a real security codebase — run end-to-end by Devin, with a human approving every change.\"",
    persona: ["CTO", "CIO", "Security"],
    tags: ["discovery", "handoff", "transition", "delivery-line"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25",
    order: 21,
    status: "active",
    lastEditedBy: "owner",
    lastEditedAt: "2026-06-25"
  }
];
