import type { ContentItem } from './schema';

export const masteryContent: ContentItem[] = [
  {
    id: "diagnosis-before-prescription",
    module: "mastery",
    type: "fact",
    title: "1. Diagnosis Before Prescription",
    body: "The single highest-leverage AE skill is discovery, not pitching. 'Feature-dumping on a demo is over' — modern buyers expect you to diagnose the problem before prescribing. Failure pattern to avoid: demo-heavy, diagnosis-light.",
    persona: [],
    tags: ["mastery", "craft", "discovery", "methodology"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "teach-tailor-take-control",
    module: "mastery",
    type: "fact",
    title: "2. Teach → Tailor → Take Control (Challenger)",
    body: "Elite AEs lead with a reframe — an insight that changes how the buyer sees their own problem — then tailor it to each stakeholder, then confidently direct the conversation. The inputs→outcomes thesis IS Benney's Challenger teach. The job is to deliver it as a reframe, not recite it as a fact.",
    persona: [],
    tags: ["mastery", "craft", "challenger", "reframe"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "earn-trust-before-pain",
    module: "mastery",
    type: "fact",
    title: "3. Earn Trust Before Naming Pain",
    body: "Audiences must connect before they'll accept a pain narrative; naming pain too early makes buyers defensive or retreat. Sequence: rapport → credibility → diagnosis → pain → implication → vision.",
    persona: [],
    tags: ["mastery", "craft", "trust", "sequence"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "multi-thread-never-single",
    module: "mastery",
    type: "fact",
    title: "4. Multi-Thread, Never Single-Thread",
    body: "The classic enterprise loss is one enthusiastic champion with no influence over finance/security/legal. Elite AEs build consensus across stakeholders. The three-persona structure (CTO/CIO/Security) is multi-threading made literal.",
    persona: [],
    tags: ["mastery", "craft", "multi-thread", "stakeholders"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "storytelling-delivery-vehicle",
    module: "mastery",
    type: "fact",
    title: "5. Storytelling as the Delivery Vehicle",
    body: "Every framework (Challenger, MEDDIC, Gap) relies on storytelling to make pain land and to disarm defensiveness. Facts inform; stories move. The proof points are raw material; the narration is the craft.",
    persona: [],
    tags: ["mastery", "craft", "storytelling"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-executive-presence",
    module: "mastery",
    type: "card",
    title: "Competency 1: Executive Presence",
    body: "**Elite tell:** Calm, unhurried, comfortable with silence; speaks less but with more weight; never fills dead air nervously.\n\n**Cognition criterion:** Confident demo facilitation.",
    persona: [],
    tags: ["mastery", "competency", "executive-presence"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-diagnostic-discovery",
    module: "mastery",
    type: "card",
    title: "Competency 2: Diagnostic Discovery",
    body: "**Elite tell:** Questions that make the exec articulate their own pain and quantify it; listens 70%, talks 30%.\n\n**Cognition criterion:** Relevant discovery.",
    persona: [],
    tags: ["mastery", "competency", "discovery"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-reframe",
    module: "mastery",
    type: "card",
    title: "Competency 3: The Reframe (Teach)",
    body: "**Elite tell:** Delivers one insight that visibly shifts the buyer's mental model (inputs→outcomes).\n\n**Cognition criterion:** Connect tech to business impact.",
    persona: [],
    tags: ["mastery", "competency", "reframe", "teach"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-tailored-framing",
    module: "mastery",
    type: "card",
    title: "Competency 4: Audience-Tailored Framing",
    body: "**Elite tell:** Same thesis, three different languages — risk for Security, portfolio economics for CIO, capability for CTO.\n\n**Cognition criterion:** Clear customer framing.",
    persona: [],
    tags: ["mastery", "competency", "tailoring", "framing"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-narrative-demo",
    module: "mastery",
    type: "card",
    title: "Competency 5: Narrative Demo Facilitation",
    body: "**Elite tell:** The demo is a story with stakes, not a feature tour; narrates the 'why' at each step; recovers gracefully when live tools misbehave.\n\n**Cognition criterion:** Structure a Devin demo + storytelling.",
    persona: [],
    tags: ["mastery", "competency", "demo", "narrative"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-objection-aikido",
    module: "mastery",
    type: "card",
    title: "Competency 6: Objection Aikido",
    body: "**Elite tell:** Welcomes objections, never defensive; reframes the hardest question (CISO's 'black box') into the strongest proof point.\n\n**Cognition criterion:** Competitive landscape + objection handling.",
    persona: [],
    tags: ["mastery", "competency", "objections", "aikido"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "competency-command-next-step",
    module: "mastery",
    type: "card",
    title: "Competency 7: Command of Next Step",
    body: "**Elite tell:** Closes with a clear, low-friction next action (pilot motion); creates urgency via real compelling events, not pressure.\n\n**Cognition criterion:** Business impact / land-and-expand.",
    persona: [],
    tags: ["mastery", "competency", "closing", "next-step"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "practice-70-30-drill",
    module: "mastery",
    type: "question",
    title: "The 70/30 Drill",
    body: "In every practice discovery pass, track talk-time. If you're talking more than ~30%, the question bank isn't doing its job — rewrite the question to be more open. Target: listen 70%, talk 30%.",
    persona: [],
    tags: ["mastery", "practice", "70-30", "drill"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "practice-reframe-timer",
    module: "mastery",
    type: "question",
    title: "Reframe-in-One-Sentence Drill (20s Timer)",
    body: "Practice delivering the inputs→outcomes thesis as a single, punchy reframe for each persona, cold, in under 20 seconds. If it takes a paragraph, it's not yet a reframe.",
    persona: ["CTO", "CIO", "Security"],
    tags: ["mastery", "practice", "reframe", "timer"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "practice-objection-cold-drill",
    module: "mastery",
    type: "question",
    title: "Objection Cold-Drill",
    body: "Fire the five hardest objections at random — especially the CISO 'black box,' the 'we already have Copilot,' and 'have you sold technical software before?' — and practice the welcoming response until it's reflexive and non-defensive.",
    persona: [],
    tags: ["mastery", "practice", "objection", "cold-drill"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "practice-live-failure",
    module: "mastery",
    type: "question",
    title: "Live-Failure Rehearsal",
    body: "Deliberately rehearse what to say when the Devin session does something unexpected live. The elite tell is calm narration ('this is exactly the kind of moment where you'd have a human approve before merge'). Practice turning a stumble into a trust-builder.",
    persona: [],
    tags: ["mastery", "practice", "failure", "recovery"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "practice-so-what-pass",
    module: "mastery",
    type: "question",
    title: "The 'So What?' Pass",
    body: "For every slide and every demo beat, force the question 'so what — why does this persona care?' If there's no crisp answer, cut it.",
    persona: [],
    tags: ["mastery", "practice", "so-what", "editing"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "narrative-arc-structure",
    module: "mastery",
    type: "story-beat",
    title: "The 40-Minute Narrative Arc",
    body: "1. **Hook** — the reframe (advertising went from inputs to outcomes; software is next).\n2. **Tension** — diagnostic discovery surfaces their numbers (senior-engineer-years on undifferentiated work, exposure windows).\n3. **Turn** — the demo: the abstract thesis made concrete on a real, security-critical repo.\n4. **Resolution** — the guarantee: outcome-pricing made contractual, de-risked.\n5. **Next step** — the low-risk pilot motion (Angular land → expand).",
    persona: ["CTO", "CIO", "Security"],
    tags: ["mastery", "narrative-arc", "structure", "40-minutes"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "benneys-background-unlock",
    module: "mastery",
    type: "fact",
    title: "Benney's Background as the Unlock",
    body: "- **Google C-Level transformation** = executive presence and 12-18mo JBP framing, already lived.\n- **The performance-marketing parallel** = a genuine teach/reframe only he can credibly deliver — earned not borrowed.\n- **BizFlash builder credibility** = the technical empathy that lets the demo narration ring true.\n- **Gap to drill:** technical-software-specific objection handling and live demo facilitation.",
    persona: [],
    tags: ["mastery", "background", "strengths", "gap"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  }
];
