import type { ContentItem } from './schema';

export const thesisContent: ContentItem[] = [
  {
    id: "inputs-to-outcomes-thesis",
    module: "thesis",
    type: "fact",
    title: "The One Idea: Inputs to Outcomes",
    body: "Software engineering is undergoing the same shift performance marketing went through twenty years ago: from paying for inputs to paying for outcomes. This reframes Devin from 'an AI coding tool' into 'the mechanism by which engineering becomes outcome-priced' — a strategy conversation the CEO/CIO will fund.",
    persona: ["CTO", "CIO", "Security"],
    tags: ["thesis", "core", "reframe"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "performance-marketing-era-1",
    module: "thesis",
    type: "fact",
    title: "Era 1 — Inputs (Advertising)",
    body: "Advertisers bought placements (a billboard, a 30-sec spot, a banner). You paid for the opportunity to get a result. Risk sat entirely with the buyer.",
    persona: [],
    tags: ["thesis", "historical-parallel", "advertising"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "performance-marketing-era-2",
    module: "thesis",
    type: "fact",
    title: "Era 2 — Measurement (Advertising)",
    body: "Google/digital made the result measurable (clicks, conversions, ROAS). The unit of value moved from 'exposure' to 'performance.'",
    persona: [],
    tags: ["thesis", "historical-parallel", "advertising", "google"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "performance-marketing-era-3",
    module: "thesis",
    type: "fact",
    title: "Era 3 — Outcomes (Advertising)",
    body: "Spend flowed to whatever delivered the business outcome per dollar. Budgets exploded not because ads got cheaper but because value became attributable. Google won because it sold outcomes, not media.",
    persona: [],
    tags: ["thesis", "historical-parallel", "advertising", "google"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "software-era-1-inputs",
    module: "thesis",
    type: "fact",
    title: "Era 1 — Inputs (Software Engineering, today's default)",
    body: "Enterprises buy engineering capacity — headcount, contractor seats, tool licenses ('seats of Copilot'). You pay for the capacity to maybe ship, regardless of what ships. Risk sits with the buyer.",
    persona: ["CIO", "CTO"],
    tags: ["thesis", "software-parallel"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "software-era-2-measurement",
    module: "thesis",
    type: "fact",
    title: "Era 2 — Measurement (Software Engineering, now)",
    body: "Agentic AI makes engineering outcomes discrete and attributable — 'this Angular upgrade, shipped, tested, merged, audit-logged' is a unit you can count, price, and verify. Devin's PR is the conversion event.",
    persona: ["CTO", "CIO"],
    tags: ["thesis", "software-parallel", "devin"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "software-era-3-outcomes",
    module: "thesis",
    type: "fact",
    title: "Era 3 — Outcomes (Software Engineering, where this goes)",
    body: "Banks will stop buying 'seats' and start buying completed, verified engineering outcomes at a known cost per unit. The org that adopts this first reallocates its scarce senior engineers from undifferentiated maintenance to differentiated product.",
    persona: ["CIO", "CTO"],
    tags: ["thesis", "software-parallel", "vision"],
    confidence: "inferred",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "bank-wedge-argument",
    module: "thesis",
    type: "fact",
    title: "Why Banks Are the Perfect Wedge",
    body: "Banks have an enormous class of work that is templatable, repeatable, high-volume, low-differentiation, and compliance-mandated: framework upgrades, version migrations, dependency patching, vulnerability remediation, test coverage. It is mandatory (regulators require it), expensive (consumes senior-engineer hours), zero competitive advantage, and perfectly outcome-shaped (each unit is discrete and verifiable).",
    persona: ["CIO", "CTO", "Security"],
    tags: ["thesis", "bank-fit", "use-case"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "room-line-bank-wedge",
    module: "thesis",
    type: "story-beat",
    title: "The Line for the Room (Bank Wedge)",
    body: "\"You are currently paying your most expensive, scarcest engineers to do work that creates no competitive advantage but cannot be skipped. That's the exact definition of work that should be priced as an outcome and delivered by an agent — with a human approving every change. We did this to advertising. It's now happening to software.\"",
    persona: ["CIO", "CTO"],
    tags: ["thesis", "delivery-line", "bank-fit"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "opportunity-cost-argument",
    module: "thesis",
    type: "fact",
    title: "The Opportunity-Cost Argument (CIO's language)",
    body: "Every senior engineer-hour on an Angular 18→19 bump is an hour not spent on the next CommBank app feature, fraud model, or customer experience. The work is infinitely repeatable (18→19→20→21...) and parallelizable — which is precisely what agents are for and humans are wasted on. Reclaimed capacity is the real product. Devin's invoice is small; the redeployed senior-engineering capacity is the ROI.",
    persona: ["CIO"],
    tags: ["thesis", "opportunity-cost", "cio-frame"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "guarantee-keystone",
    module: "thesis",
    type: "fact",
    title: "The Devin Productivity Guarantee = Outcome-Pricing Made Contractual",
    body: "Cognition guarantees Devin delivers at least as much engineering value as you consume. Output measured in equivalent engineering hours, converted to dollars, compared against usage. If value falls short, Cognition issues free usage credits to cover the gap, up to $10M. Validated by 126 engineers across 8 enterprise customers. Real-time dashboard tracks it continuously. Historical data is immutable. Formal evaluation one month before renewal.",
    persona: ["CIO", "CTO", "Security"],
    tags: ["thesis", "guarantee", "outcome-pricing", "differentiator"],
    confidence: "verified",
    source: { label: "devin.ai/guarantee", url: "https://devin.ai/guarantee/" },
    dateAdded: "2026-06-25"
  },
  {
    id: "guarantee-unbundler-line",
    module: "thesis",
    type: "story-beat",
    title: "The Guarantee as Competitive Unbundler",
    body: "\"A Copilot or Cursor seat is a license to a human — you pay whether or not anything ships, and the tool's contribution is impossible to isolate from the developer's. Devin is the opposite: the work is done autonomously, so the output itself can be measured in equivalent engineering-hours, dollarised, and put on a dashboard — and Cognition will guarantee it breaks even or credit you the difference, up to $10M. You cannot guarantee the value of an autocomplete. You can guarantee the value of a completed, verified outcome. That's the whole difference between buying inputs and buying outcomes.\"",
    persona: ["CIO", "CTO"],
    tags: ["thesis", "guarantee", "competitive", "delivery-line"],
    confidence: "verified",
    source: { label: "devin.ai/guarantee", url: "https://devin.ai/guarantee/" },
    dateAdded: "2026-06-25"
  },
  {
    id: "cfo-headline-framing",
    module: "thesis",
    type: "story-beat",
    title: "Headline for the CFO-Minded CIO",
    body: "\"This is the only AI engineering tool I can put in front of you where the vendor is contractually accountable for the value, not just the activity. Tokens consumed and lines generated are vanity metrics. Equivalent engineering-hours delivered, guaranteed, is a P&L line.\"",
    persona: ["CIO"],
    tags: ["thesis", "guarantee", "delivery-line", "cio-frame"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "non-linear-scaling",
    module: "thesis",
    type: "fact",
    title: "Non-Linear Scaling (The Structural Unlock)",
    body: "IDE assistants (Copilot/Cursor/Claude Code) make each human somewhat faster — output still scales linearly with headcount. Devin executes tasks autonomously and in parallel (MultiDevin: 1 manager + up to 10 workers, auto-merged). Throughput scales with agents you spin up, not seats you hire. For a bank: senior engineering is the scarcest, most expensive, hardest-to-hire resource. Decoupling mandatory-maintenance throughput from senior headcount is the structural prize.",
    persona: ["CTO", "CIO"],
    tags: ["thesis", "non-linear", "multidevin", "differentiator"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "non-linear-scaling-line",
    module: "thesis",
    type: "story-beat",
    title: "The Non-Linear Scaling Line",
    body: "\"With an IDE assistant, doubling your upgrade throughput means doubling the humans doing upgrades. With Devin, it means starting more agents — while your senior engineers move to the work only they can do. That's not a productivity bump; it's breaking the link between maintenance load and headcount.\"",
    persona: ["CTO", "CIO"],
    tags: ["thesis", "non-linear", "delivery-line"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "reframe-drill-cto",
    module: "thesis",
    type: "question",
    title: "Reframe Drill: One sentence for the CTO",
    body: "Deliver the inputs→outcomes thesis as a single, punchy reframe for the CTO (technical capability frame) in under 20 seconds.",
    persona: ["CTO"],
    tags: ["thesis", "drill", "reframe"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "reframe-drill-cio",
    module: "thesis",
    type: "question",
    title: "Reframe Drill: One sentence for the CIO",
    body: "Deliver the inputs→outcomes thesis as a single, punchy reframe for the CIO (portfolio economics frame) in under 20 seconds.",
    persona: ["CIO"],
    tags: ["thesis", "drill", "reframe"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "reframe-drill-security",
    module: "thesis",
    type: "question",
    title: "Reframe Drill: One sentence for Security",
    body: "Deliver the inputs→outcomes thesis as a single, punchy reframe for the Head of Compliance & Security (risk/auditability frame) in under 20 seconds.",
    persona: ["Security"],
    tags: ["thesis", "drill", "reframe"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  },
  {
    id: "meta-move-building-in-devin",
    module: "thesis",
    type: "fact",
    title: "The Meta-Move: Building This in Devin",
    body: "Building this prep environment in Devin is itself the proof. When asked 'are you actually a power user of agentic tools?', the honest answer is 'I built my interview prep operating system by directing Devin to a shipped outcome — here it is.'",
    persona: [],
    tags: ["thesis", "meta", "credibility"],
    confidence: "verified",
    source: null,
    dateAdded: "2026-06-25"
  }
];
