#!/usr/bin/env node

/**
 * apply-content.mjs — Applies an exported content.export.json to src/content/ files.
 *
 * Usage:
 *   node scripts/apply-content.mjs content.export.json
 *
 * This is a build-time helper — it is never shipped to the browser.
 * It reads the export JSON and writes valid TypeScript files to src/content/.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const CONTENT_DIR = resolve(ROOT, 'src/content');

// Module name → file name mapping
const MODULE_FILE_MAP = {
  'thesis': 'thesis.ts',
  'account-intel': 'accountIntel.ts',
  'repo-rationale': 'repoRationale.ts',
  'discovery': 'discovery.ts',
  'devin-narrative': 'devinNarrative.ts',
  'competitive': 'competitive.ts',
  'mastery': 'mastery.ts',
};

function moduleToVarName(moduleName) {
  return moduleName.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Content';
}

function moduleToFileName(moduleName) {
  return MODULE_FILE_MAP[moduleName] || moduleName.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + '.ts';
}

function escapeForTS(str) {
  return JSON.stringify(str);
}

function generateModuleFile(moduleName, items) {
  const varName = moduleToVarName(moduleName);
  const sortedItems = items
    .filter(i => i.status === 'active')
    .sort((a, b) => a.order - b.order);

  const lines = [];
  lines.push(`import type { ContentItem } from './schema';`);
  lines.push('');
  lines.push(`export const ${varName}: ContentItem[] = [`);

  for (const item of sortedItems) {
    lines.push('  {');
    lines.push(`    id: ${escapeForTS(item.id)},`);
    lines.push(`    module: ${escapeForTS(item.module)},`);
    lines.push(`    type: ${escapeForTS(item.type)},`);
    lines.push(`    title: ${escapeForTS(item.title)},`);
    lines.push(`    body: ${escapeForTS(item.body)},`);
    lines.push(`    persona: ${JSON.stringify(item.persona)},`);
    lines.push(`    tags: ${JSON.stringify(item.tags)},`);
    lines.push(`    confidence: ${escapeForTS(item.confidence)},`);

    if (item.source === null) {
      lines.push(`    source: null,`);
    } else {
      lines.push(`    source: { label: ${escapeForTS(item.source.label)}, url: ${escapeForTS(item.source.url)} },`);
    }

    lines.push(`    dateAdded: ${escapeForTS(item.dateAdded)},`);
    lines.push(`    order: ${item.order},`);
    lines.push(`    status: ${escapeForTS(item.status)},`);
    lines.push(`    lastEditedBy: ${escapeForTS(item.lastEditedBy)},`);
    lines.push(`    lastEditedAt: ${escapeForTS(item.lastEditedAt)}`);
    lines.push('  },');
  }

  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

function generateIndexFile(moduleNames) {
  const lines = [];

  lines.push(`/**`);
  lines.push(` * Content Index — auto-generated by scripts/apply-content.mjs`);
  lines.push(` * Do not edit manually — run the script after exporting from the app.`);
  lines.push(` */`);
  lines.push('');
  lines.push(`import type { ContentItem } from './schema';`);
  lines.push(`import { validateContentItem } from './schema';`);

  for (const mod of moduleNames) {
    const varName = moduleToVarName(mod);
    const fileName = moduleToFileName(mod).replace('.ts', '');
    lines.push(`import { ${varName} } from './${fileName}';`);
  }

  lines.push('');
  lines.push('const rawContent: ContentItem[] = [');
  for (const mod of moduleNames) {
    const varName = moduleToVarName(mod);
    lines.push(`  ...${varName},`);
  }
  lines.push('];');
  lines.push('');
  lines.push('rawContent.forEach((item, index) => {');
  lines.push('  validateContentItem(item, index);');
  lines.push('});');
  lines.push('');
  lines.push('const ids = rawContent.map(item => item.id);');
  lines.push("const duplicates = ids.filter((id, i) => ids.indexOf(id) !== i);");
  lines.push('if (duplicates.length > 0) {');
  lines.push("  console.warn(`[Content Validator] Duplicate IDs found: ${duplicates.join(', ')}`);");
  lines.push('}');
  lines.push('');
  lines.push('export const allContent: ContentItem[] = rawContent;');
  lines.push('');
  lines.push('export function getContentByModule(module: string): ContentItem[] {');
  lines.push("  return allContent.filter(item => item.module === module);");
  lines.push('}');
  lines.push('');
  lines.push('export function getContentByPersona(persona: string): ContentItem[] {');
  lines.push("  return allContent.filter(item => item.persona.includes(persona as ContentItem['persona'][number]));");
  lines.push('}');
  lines.push('');
  lines.push('export function getContentByType(type: string): ContentItem[] {');
  lines.push("  return allContent.filter(item => item.type === type);");
  lines.push('}');
  lines.push('');
  lines.push('export function getContentByTag(tag: string): ContentItem[] {');
  lines.push("  return allContent.filter(item => item.tags.includes(tag));");
  lines.push('}');
  lines.push('');
  lines.push('export function getDrillableItems(): ContentItem[] {');
  lines.push("  return allContent.filter(item =>");
  lines.push("    item.type === 'question' || item.type === 'objection' || item.type === 'story-beat'");
  lines.push('  );');
  lines.push('}');
  lines.push('');
  lines.push('export function getSourceItems(): ContentItem[] {');
  lines.push("  return allContent.filter(item => item.source !== null);");
  lines.push('}');
  lines.push('');
  lines.push("export type { ContentItem, ModuleName, BuiltInModuleName, Persona, Confidence, ContentStatus } from './schema';");
  lines.push('');

  return lines.join('\n');
}

// --- Main ---

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('Usage: node scripts/apply-content.mjs <content.export.json>');
  process.exit(1);
}

const inputFile = resolve(process.cwd(), args[0]);
if (!existsSync(inputFile)) {
  console.error(`File not found: ${inputFile}`);
  process.exit(1);
}

const raw = readFileSync(inputFile, 'utf8');
let payload;
try {
  payload = JSON.parse(raw);
} catch (e) {
  console.error(`Invalid JSON: ${e.message}`);
  process.exit(1);
}

if (!Array.isArray(payload.items)) {
  console.error('Export file must have an "items" array');
  process.exit(1);
}

console.log(`Loaded ${payload.items.length} items from export`);

// Group items by module
const byModule = new Map();
for (const item of payload.items) {
  if (!byModule.has(item.module)) {
    byModule.set(item.module, []);
  }
  byModule.get(item.module).push(item);
}

// Use module order from export if available, otherwise from items
const moduleOrder = payload.modules || Array.from(byModule.keys());

// Write module files
for (const [moduleName, items] of byModule) {
  const fileName = moduleToFileName(moduleName);
  const filePath = resolve(CONTENT_DIR, fileName);
  const content = generateModuleFile(moduleName, items);
  writeFileSync(filePath, content);
  console.log(`  Wrote ${filePath} (${items.filter(i => i.status === 'active').length} active items)`);
}

// Write index file
const indexPath = resolve(CONTENT_DIR, 'index.ts');
const indexContent = generateIndexFile(moduleOrder);
writeFileSync(indexPath, indexContent);
console.log(`  Wrote ${indexPath}`);

console.log('\nDone! Run `npm run build` to verify the output.');
